### ISSUE TITLE
Missing files and build

### ISSUE THREAD

**Issue by StrangerGithuber** [4miau/Abigail-Williams#1]
Hello
When I am using pnpm typecheck command then it doesn't build but giving me tsc config is missing and therefore can't build. Plus I don't find the env file either what options need there.

**Comment by 4miau** [comment]
I have committed a few updates to slightly help such as an .env.example, the tsconfig, eslint configurations, and such however as my README states, you will need to learn to re-create certain files. Library requirements are in the README. If you learn the discord-akairo framework then this will simplify your work.
